### ISSUE TITLE
bug: .Item-quote 줄바꿈 처리 추가

### ISSUE THREAD

**Issue by cbcruk** [cbcruk/zitat#4]
https://github.com/cbcruk/zitat/blob/894a24d370c848257f0f94fdc70825b7187be568/components/List.js#L49-L52

```css
{
  white-space: `pre-line`
}
```
